
import { pricingService } from '../pricing';
import { cotizacionesService } from '../cotizaciones';
import { pdfService } from '../pdfService';
import { chatService } from './chatService';
import { supabase } from '../supabase';
import type { ModuloAdicional } from '../../types/cotizaciones';

export interface AiQuoteTrigger {
    dte_volume: number;
    plan_id?: string;
    modules?: string[];
    include_imp?: boolean;
    lead_id: string;
    conversation_id: string;
    company_id: string;
}

export const aiQuoteService = {
    /**
     * Processes a trigger from the AI to generate a real quote.
     */
    async processAiQuote(trigger: AiQuoteTrigger) {
        try {
            console.log('AI Trigger received:', trigger);

            // 1. Get Pricing Configuration
            const config = await pricingService.getPricingConfig();

            // 2. Select Plan based on DTEs or ID
            let selectedItem = config.planes.find(p => p.id === trigger.plan_id);
            if (!selectedItem) {
                const planResult = await pricingService.getPlanByDTEs(trigger.dte_volume);
                if (planResult) selectedItem = planResult;
            }

            if (!selectedItem) {
                throw new Error(`No se encontró un plan adecuado para ${trigger.dte_volume} DTEs`);
            }

            // 3. Map Modules
            const selectedModulesItems = config.modulos.filter(m => trigger.modules?.includes(m.id || ''));
            const modulosAdicionales: ModuloAdicional[] = selectedModulesItems.map(m => ({
                nombre: m.nombre,
                costo_anual: m.precio_anual,
                costo_mensual: m.precio_mensual,
                descripcion: m.descripcion
            }));

            // 4. Calculate Totals using core logic
            const totals = cotizacionesService.calcularTotales({
                volumen_dtes: trigger.dte_volume,
                plan_nombre: selectedItem.nombre,
                costo_plan_anual: selectedItem.precio_anual,
                costo_plan_mensual: selectedItem.precio_mensual,
                costo_implementacion: selectedItem.costo_unico || 0,
                incluir_implementacion: trigger.include_imp ?? true,
                modulos_adicionales: modulosAdicionales,
                servicio_whatsapp: trigger.modules?.includes('whatsapp') || false,
                servicio_personalizacion: false
            });

            // 5. Create the Quote in DB with real lead name
            const { data: leadData } = await supabase.from('marketing_leads').select('name').eq('id', trigger.lead_id).single();

            const newQuote = await cotizacionesService.createCotizacion({
                company_id: trigger.company_id,
                lead_id: trigger.lead_id,
                nombre_cliente: leadData?.name || 'Cliente de AI',
                volumen_dtes: trigger.dte_volume,
                plan_nombre: selectedItem.nombre,
                costo_plan_anual: selectedItem.precio_anual,
                costo_plan_mensual: selectedItem.precio_mensual,
                costo_implementacion: selectedItem.costo_unico || 0,
                incluir_implementacion: trigger.include_imp ?? true,
                modulos_adicionales: modulosAdicionales,
                servicio_whatsapp: trigger.modules?.includes('whatsapp') || false,
                costo_whatsapp: totals.costo_whatsapp,
                servicio_personalizacion: false,
                costo_personalizacion: totals.costo_personalizacion,
                subtotal_anual: totals.subtotal_anual,
                subtotal_mensual: totals.subtotal_mensual,
                descuento_porcentaje: 0,
                descuento_monto: totals.descuento_monto,
                iva_porcentaje: totals.iva_porcentaje,
                iva_monto: totals.iva_monto,
                total_anual: totals.total_anual,
                total_mensual: totals.total_mensual,
                estado: 'enviada'
            });

            // 6. Generate PDF
            console.log('Generating PDF for auto-quote...');
            const pdfUrl = await pdfService.generateAndUploadQuotePDF(newQuote);

            // 7. Send back to the channel correctly
            const message = `¡Listo! He preparado una propuesta comercial personalizada para ti basada en lo que conversamos. Aquí puedes descargarla:\n\n📄 ${pdfUrl}`;

            await chatService.sendMessage(trigger.conversation_id, message, 'file', 'outbound', {
                url: pdfUrl,
                fileName: `Propuesta_Automatica_${new Date().getTime()}.pdf`,
                isAutoGenerated: true
            });

            return { success: true, quoteId: newQuote.id, pdfUrl };

        } catch (error) {
            console.error('Error in processAiQuote:', error);
            throw error;
        }
    }
};
